# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the [issue template](https://github.com/anDiary/anDiary/tree/main/.github/ISSUE_TEMPLATE/bug_report.md)!

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
# newPRWelcomeComment: >
#   Thanks for opening this pull request. Make sure to check out our [contributing guidelines](#).
