printWidth: 80
tabWidth: 2
useTabs: true
semi: false
singleQuote: true
quoteProps: "as-needed"
jsxSingleQuote: false
trailingComma: "none"
bracketSpacing: true
bracketSameLine: true
arrowParens: "always"
requirePragma: false
insertPragma: false
proseWrap: "preserve"
htmlWhitespaceSensitivity: "css"
endOfLine: "lf"
embeddedLanguageFormatting: "auto"
singleAttributePerLine: false
